site_name: MMB Forecasting Project Documentation

theme:
  name: material

nav:
  - Home: index.md
  - Software environments: system.md
  - Project layout: layout.md
  - Process data: data.md
  - Generate forecast: forecast.md
  - Add model: model.md
  - Present results: application.md

markdown_extensions:
  - def_list
  - admonition
  - pymdownx.tabbed
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js