site_name: MMB Forecasting Project Documentation

theme:
  name: material

nav:
  - Home: index.md # done
  - Software environments: system.md # done
  - Project layout: layout.md # done
  - Process data: data.md # done
  - Generate forecast: forecast.md # done
  - Add model: model.md # done
  - Present results: application.md # done
  - Important readings: reference.md # done

markdown_extensions:
  - def_list
  - admonition
  - pymdownx.tabbed
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.snippets
  - attr_list

extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js